services:
  redis:
    hostname: redis
    container_name: redis
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - laudspeaker_default

  postgres:
    image: postgres:14.4-alpine
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: laudspeaker
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - laudspeaker_default

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    hostname: pgbouncer
    environment:
      - LISTEN_PORT=6432
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - DB_NAME=laudspeaker
      - AUTH_TYPE=scram-sha-256
      - POOL_MODE=transaction
      - MAX_DB_CONNECTIONS=100
      - MAX_CLIENT_CONN=1000
      - MIN_POOL_SIZE=5
      - DEFAULT_POOL_SIZE=100
      - RESERVE_POOL_SIZE=0
      - IGNORE_STARTUP_PARAMETERS=lock_timeout,statement_timeout,idle_in_transaction_session_timeout
      - ADMIN_USERS=${POSTGRES_USER:-postgres}
    ports:
      - "6432:6432"
    depends_on:
      - postgres
    networks:
      - laudspeaker_default

  mongo:
    image: "mongo:latest"
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    command: "--bind_ip_all --replSet rs0"
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "admin",
          "--port",
          "27017",
          "--eval",
          "db.adminCommand('ping').ok",
        ]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - laudspeaker_default

  clickhouse:
    hostname: clickhouse
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    restart: on-failure
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 2s
      retries: 20
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - laudspeaker_default

  #### START kafka related containers
  zoo1:
    image: bitnami/zookeeper:latest
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_SERVERS: zoo1:2888:3888
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - laudspeaker_default

  kafka1:
    image: bitnami/kafka:3.6.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "29092:29092"
      - "9092:9092"
    healthcheck:
      test: kafka-cluster.sh cluster-id --bootstrap-server kafka1:19092 || exit 1
      interval: 1s
      timeout: 60s
      retries: 60
    environment:
      KAFKA_CFG_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://kafka1:29092,DEV://kafka1:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://host.docker.internal:29092,DEV://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DEV:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_PROTOCOL: PLAINTEXT
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_TLS_CLIENT_AUTH: none
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zoo1
    networks:
      - laudspeaker_default

  #### END kafka related containers

  #### START kafka connect related containers
  kafka-connect1:
    image: bitnami/kafka:latest
    hostname: kafka-connect1
    container_name: kafka-connect1
    healthcheck:
      test: ["CMD", "curl", "localhost:8083"]
      interval: 5s
      timeout: 2s
      retries: 20
    ports:
      - "8083:8083"
    volumes:
      - ./local-env/kafkaconnect:/opt/bitnami/kafka-connect
    depends_on:
      kafka1:
        condition: service_healthy
    networks:
      - laudspeaker_default
    command:
      - bash
      - -c
      - /opt/bitnami/kafka/bin/connect-distributed.sh /opt/bitnami/kafka-connect/connect.properties
  #### END kafka connect related containers

  init-environment:
    build:
      context: ./local-env/
      dockerfile: Dockerfile.initenv
    container_name: init-environment
    depends_on:
      mongo:
        condition: service_healthy
      kafka1:
        condition: service_started
      clickhouse:
        condition: service_healthy
      kafka-connect1:
        condition: service_healthy
      s3:
        condition: service_healthy
    networks:
      - laudspeaker_default
    command:
      - "environment"

  s3:
    image: quay.io/minio/minio
    command: "server /data --console-address :9123"
    ports:
      - "9123:9123"
      - "9001:9000"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: 12345678
    container_name: s3
    networks:
      - laudspeaker_default

  ping-server:
    image: jaredhanson11/ping-server:latest
    container_name: ping-server
    ports:
      - "8555:8555"
    environment:
      PORT: 8555
    networks:
      - laudspeaker_default

  laudspeaker-web:
    profiles:
      - "testing"
    image: ${LAUDSPEAKER_IMAGE:-laudspeaker/laudspeaker:latest}
    container_name: laudspeaker-web
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8080"]
      interval: 5s
      timeout: 30s
      retries: 20
      start_period: 60s
    depends_on:
      init-environment:
        condition: service_completed_successfully
      s3-createbuckets:
        condition: service_completed_successfully
    env_file:
      - ./local-env/env-docker-compose
    networks:
      - laudspeaker_default

  laudspeaker-queue:
    profiles:
      - "testing"
    image: ${LAUDSPEAKER_IMAGE:-laudspeaker/laudspeaker:latest}
    container_name: laudspeaker-queue
    command: "queue"
    healthcheck:
      test: '[ $(find /tmp/laudspeaker-healthcheck-queue -mmin -1 | wc -l) -eq 1 ] || false'
      interval: 10s
      timeout: 30s
      retries: 10
    depends_on:
      laudspeaker-web:
        condition: service_healthy
    env_file:
      - ./local-env/env-docker-compose
    networks:
      - laudspeaker_default

  laudspeaker-cron:
    profiles:
      - "testing"
    image: ${LAUDSPEAKER_IMAGE:-laudspeaker/laudspeaker:latest}
    container_name: laudspeaker-cron
    command: "cron"
    healthcheck:
      test: '[ $(find /tmp/laudspeaker-healthcheck-cron -mmin -1 | wc -l) -eq 1 ] || false'
      interval: 10s
      timeout: 30s
      retries: 10
    depends_on:
      laudspeaker-web:
        condition: service_healthy
    env_file:
      - ./local-env/env-docker-compose
    networks:
      - laudspeaker_default

  s3-createbuckets:
    image: minio/mc
    profiles:
      - "testing"
      - gui
    depends_on:
      s3:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add s3 http://s3:9000 test 12345678;
      /usr/bin/mc mb s3/$$AWS_S3_CUSTOMERS_IMPORT_BUCKET;
      /usr/bin/mc mb s3/$$AWS_S3_BUCKET;
      exit 0;
      "
    env_file:
      - ./local-env/env-docker-compose
    networks:
      - laudspeaker_default

  init-connectors:
    build:
      context: ./local-env/
      dockerfile: Dockerfile.initenv
    container_name: init-connectors
    profiles:
      - testing
    depends_on:
      laudspeaker-web:
        condition: service_healthy
    networks:
      - laudspeaker_default
    command:
      - "connectors"

  # GUIs for all supporting services.
  # currently:
  #   - no gui setup for postgres
  #   - clickhouse gui is deployed with the clickhouse server

  kafka-gui:
    container_name: kafka-gui
    image: provectuslabs/kafka-ui:latest
    profiles:
      - gui
    ports:
      - 8090:8080
    depends_on:
      kafka1:
        condition: service_started
      kafka-connect1:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: laudspeaker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect1:8083
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: kafka-connect
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - laudspeaker_default

  redis-gui:
    container_name: redis-gui
    image: redis/redisinsight:latest
    profiles:
      - gui
    ports:
      - 8091:5540
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:5540/api/health/ || exit 1
    networks:
      - laudspeaker_default

  init-guis:
    profiles:
      - gui
    build:
      context: ./local-env/
      dockerfile: Dockerfile.initenv
    container_name: init-gui
    depends_on:
      redis-gui:
        condition: service_healthy
    networks:
      - laudspeaker_default
    command:
      - "guis"

networks:
  laudspeaker_default:
    driver: bridge
    name: laudspeaker_default
